// <auto-generated />
using HealthPlatform.Models.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace HealthPlatform.Migrations
{
    [DbContext(typeof(WorkoutContext))]
    partial class WorkoutContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("HealthPlatform.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Duration");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("HealthPlatform.Models.ActivityType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivityId");

                    b.Property<int?>("GymId");

                    b.Property<int?>("RunningId");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId");

                    b.HasIndex("GymId");

                    b.HasIndex("RunningId");

                    b.ToTable("Types");
                });

            modelBuilder.Entity("HealthPlatform.Models.Excercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GymId");

                    b.Property<string>("Name");

                    b.Property<int>("Reps");

                    b.Property<int>("Sets");

                    b.Property<int>("Weight");

                    b.HasKey("Id");

                    b.HasIndex("GymId");

                    b.ToTable("Exercises");
                });

            modelBuilder.Entity("HealthPlatform.Models.Gym", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("Gym");
                });

            modelBuilder.Entity("HealthPlatform.Models.Running", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Distance");

                    b.Property<string>("Pace");

                    b.Property<string>("Time");

                    b.HasKey("Id");

                    b.ToTable("Running");
                });

            modelBuilder.Entity("HealthPlatform.Models.ActivityType", b =>
                {
                    b.HasOne("HealthPlatform.Models.Activity")
                        .WithMany("Types")
                        .HasForeignKey("ActivityId");

                    b.HasOne("HealthPlatform.Models.Gym", "Gym")
                        .WithMany()
                        .HasForeignKey("GymId");

                    b.HasOne("HealthPlatform.Models.Running", "Running")
                        .WithMany()
                        .HasForeignKey("RunningId");
                });

            modelBuilder.Entity("HealthPlatform.Models.Excercise", b =>
                {
                    b.HasOne("HealthPlatform.Models.Gym")
                        .WithMany("Exercises")
                        .HasForeignKey("GymId");
                });
#pragma warning restore 612, 618
        }
    }
}
